#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


NAME_RE = re.compile(r"^[A-Za-z0-9_.+\\[-][A-Za-z0-9_.+\\[-]*$")
SYMBOL_RE = re.compile(r"^bx_[A-Za-z0-9_]+_main$")


def read_manifest(path: Path) -> dict[str, object]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"dispatch manifest is not an object: {path}")
    if data.get("manifest_version") != 1:
        raise SystemExit("dispatch manifest manifest_version must be 1")
    return data


def load_entries(manifest: dict[str, object], field: str) -> list[dict[str, str]]:
    raw = manifest.get(field)
    if not isinstance(raw, list):
        raise SystemExit(f"dispatch manifest missing list: {field}")
    entries: list[dict[str, str]] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise SystemExit(f"{field}[{index}] must be an object")
        name = item.get("name")
        main = item.get("main")
        if not isinstance(name, str) or not NAME_RE.match(name):
            raise SystemExit(f"{field}[{index}] has invalid applet name")
        if not isinstance(main, str) or not SYMBOL_RE.match(main):
            raise SystemExit(f"{field}[{index}] has invalid main symbol")
        entries.append({"name": name, "main": main})
    return entries


def validate_entries(boot_critical: list[dict[str, str]], applets: list[dict[str, str]]) -> None:
    if [entry["name"] for entry in boot_critical[:2]] != ["init", "switch_root"]:
        raise SystemExit("boot-critical dispatch order must begin with init, switch_root")

    seen: dict[str, str] = {}
    for group, entries in (("boot_critical", boot_critical), ("applets", applets)):
        for entry in entries:
            previous = seen.get(entry["name"])
            if previous is not None:
                raise SystemExit(
                    f"duplicate dispatch applet name {entry['name']!r} in {group}; first seen in {previous}"
                )
            seen[entry["name"]] = group


def dispatch_names(boot_critical: list[dict[str, str]], applets: list[dict[str, str]]) -> list[str]:
    return [entry["name"] for entry in boot_critical] + [entry["name"] for entry in applets]


def c_string(value: str) -> str:
    return json.dumps(value)


def write_dispatch_c(
    *,
    output: Path,
    manifest_path: Path,
    boot_critical: list[dict[str, str]],
    applets: list[dict[str, str]],
) -> None:
    entries = [
        (entry["name"], entry["main"], True)
        for entry in boot_critical
    ] + [
        (entry["name"], entry["main"], False)
        for entry in applets
    ]

    lines: list[str] = []
    lines.append("/* Generated by tools/dispatch/generate_dispatch_tables.py. */")
    lines.append(f"/* Source: {manifest_path.as_posix()} */")
    lines.append("#include <stddef.h>")
    lines.append("#include <string.h>")
    lines.append("")
    lines.append('#include "applets.h"')
    lines.append('#include "dispatch/dispatch.h"')
    lines.append("")
    lines.append("static const struct bx_dispatch_entry bx_dispatch_entries[] = {")
    for name, main, boot in entries:
        lines.append(f"    {{{c_string(name)}, {main}, {'true' if boot else 'false'}}},")
    lines.append("};")
    lines.append("")
    lines.append("size_t bx_dispatch_count(void) {")
    lines.append("    return sizeof(bx_dispatch_entries) / sizeof(bx_dispatch_entries[0]);")
    lines.append("}")
    lines.append("")
    lines.append("const struct bx_dispatch_entry* bx_dispatch_at(size_t index) {")
    lines.append("    if (index >= bx_dispatch_count()) {")
    lines.append("        return NULL;")
    lines.append("    }")
    lines.append("    return &bx_dispatch_entries[index];")
    lines.append("}")
    lines.append("")
    lines.append("bx_applet_main_t bx_dispatch_find(const char* name) {")
    lines.append("    if (name == NULL) {")
    lines.append("        return NULL;")
    lines.append("    }")
    lines.append("    for (size_t i = 0; i < bx_dispatch_count(); i++) {")
    lines.append("        if (strcmp(bx_dispatch_entries[i].name, name) == 0) {")
    lines.append("            return bx_dispatch_entries[i].main;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return NULL;")
    lines.append("}")
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> int:
    if len(argv) == 3 and argv[1] == "--meson-list":
        manifest_path = Path(argv[2])
        manifest = read_manifest(manifest_path)
        boot_critical = load_entries(manifest, "boot_critical")
        applets = load_entries(manifest, "applets")
        validate_entries(boot_critical, applets)
        sys.stdout.write("\n".join(dispatch_names(boot_critical, applets)) + "\n")
        return 0

    if len(argv) != 3:
        raise SystemExit(f"usage: {Path(argv[0]).name} APPLETS_JSON OUTPUT_C")

    manifest_path = Path(argv[1])
    output = Path(argv[2])
    manifest = read_manifest(manifest_path)
    boot_critical = load_entries(manifest, "boot_critical")
    applets = load_entries(manifest, "applets")
    validate_entries(boot_critical, applets)
    write_dispatch_c(
        output=output,
        manifest_path=manifest_path,
        boot_critical=boot_critical,
        applets=applets,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
