#ifndef BX_APPLETS_TEXT_EDIT_BX_VIM_CONFIG_H
#define BX_APPLETS_TEXT_EDIT_BX_VIM_CONFIG_H

#ifndef BX_EDIT_VIM_RUNTIME_INSTALL_DIR
#error "BX_EDIT_VIM_RUNTIME_INSTALL_DIR must be defined"
#endif

#ifndef BX_EDIT_VIM_RUNTIME_SOURCE_DIR
#error "BX_EDIT_VIM_RUNTIME_SOURCE_DIR must be defined"
#endif

#define BX_VIM_EMBEDDED 1
#define BX_VIM_CURATED_RUNTIME 1

#endif /* BX_APPLETS_TEXT_EDIT_BX_VIM_CONFIG_H */
