#include <stdio.h>
#include <string.h>

#include "rg_generate.h"

static const char *const rg_completion_words[] = {
    "--after-context", "--before-context", "--binary", "--block-buffered",
    "--color", "--colors", "--context", "--count", "--crlf", "--debug",
    "--encoding", "--files", "--files-with-matches", "--files-without-match",
    "--fixed-strings", "--follow", "--generate", "--glob", "--glob-case-insensitive",
    "--heading", "--hidden", "--hyperlink-format", "--ignore", "--ignore-file",
    "--ignore-file-case-insensitive", "--ignore-files", "--ignore-global",
    "--ignore-messages", "--json", "--line-buffered", "--line-number", "--max-count",
    "--max-depth", "--max-filesize", "--multiline", "--multiline-dotall",
    "--no-config", "--no-filename", "--no-heading", "--null", "--null-data",
    "--one-file-system", "--passthru", "--path-separator", "--pcre2", "--pre",
    "--pre-glob", "--pretty", "--quiet", "--regexp", "--replace", "--search-zip",
    "--smart-case", "--sort", "--sort-files", "--stats", "--text", "--threads",
    "--trace", "--trim", "--type", "--type-add", "--type-clear", "--type-list",
    "--unrestricted", "--vimgrep", "--with-filename", "--word-regexp",
    "-0", "-A", "-B", "-C", "-E", "-F", "-H", "-I", "-L", "-M", "-N", "-P",
    "-S", "-U", "-V", "-a", "-c", "-e", "-f", "-g", "-h", "-i", "-j", "-l",
    "-m", "-n", "-o", "-p", "-r", "-s", "-t", "-u", "-v", "-w", "-x", "-z",
    NULL,
};

static void bx_rg_emit_completion_words(void) {
    for (size_t i = 0; rg_completion_words[i]; i++) {
        if (i > 0)
            fputc(' ', stdout);
        fputs(rg_completion_words[i], stdout);
    }
}

static void bx_rg_generate_man(const char *progname) {
    printf(".TH %s 1\n", progname);
    puts(".SH NAME");
    printf("%s \\- bx ripgrep-compatible search frontend\n", progname);
    puts(".SH SYNOPSIS");
    printf("\\fB%s\\fP [\\fIOPTIONS\\fP] \\fIPATTERN\\fP [\\fIPATH\\fP...]\n", progname);
    puts(".SH DESCRIPTION");
    puts("Search files and directories with ripgrep-style flags.");
    puts(".SH GENERATED OUTPUT");
    puts("This manual page was generated by bx --generate=man.");
}

static void bx_rg_generate_bash(const char *progname) {
    printf("_%s_complete() {\n", progname);
    puts("    local cur=\"${COMP_WORDS[COMP_CWORD]}\"");
    puts("    local words=\"$(cat <<'__BX_RG_WORDS__'");
    bx_rg_emit_completion_words();
    puts("\n__BX_RG_WORDS__");
    puts(")\"");
    puts("    COMPREPLY=( $(compgen -W \"$words\" -- \"$cur\") )");
    puts("}");
    printf("complete -F _%s_complete %s\n", progname, progname);
}

static void bx_rg_generate_zsh(const char *progname) {
    puts("#compdef rg");
    puts("_arguments '*:arg:->args'");
    puts("case $state in");
    puts("  args)");
    puts("    _values 'rg options' \\");
    for (size_t i = 0; rg_completion_words[i]; i++)
        printf("      '%s' \\\n", rg_completion_words[i]);
    puts("    ;;");
    puts("esac");
    (void)progname;
}

static void bx_rg_generate_fish(const char *progname) {
    for (size_t i = 0; rg_completion_words[i]; i++)
        printf("complete -c %s -f -a '%s'\n", progname, rg_completion_words[i]);
}

static void bx_rg_generate_powershell(const char *progname) {
    printf("Register-ArgumentCompleter -CommandName '%s' -ScriptBlock {\n", progname);
    puts("    param($wordToComplete, $commandAst, $cursorPosition)");
    for (size_t i = 0; rg_completion_words[i]; i++) {
        printf("    [System.Management.Automation.CompletionResult]::new('%s','%s','ParameterValue','%s')\n",
               rg_completion_words[i], rg_completion_words[i], rg_completion_words[i]);
    }
    puts("}");
}

bool bx_rg_generate_output(const char *progname, const char *kind) {
    if (!kind)
        return false;
    if (strcmp(kind, "man") == 0) {
        bx_rg_generate_man(progname);
        return true;
    }
    if (strcmp(kind, "complete-bash") == 0) {
        bx_rg_generate_bash(progname);
        return true;
    }
    if (strcmp(kind, "complete-zsh") == 0) {
        bx_rg_generate_zsh(progname);
        return true;
    }
    if (strcmp(kind, "complete-fish") == 0) {
        bx_rg_generate_fish(progname);
        return true;
    }
    if (strcmp(kind, "complete-powershell") == 0) {
        bx_rg_generate_powershell(progname);
        return true;
    }
    fprintf(stderr, "%s: error parsing flag --generate: choice '%s' is unrecognized\n",
            progname, kind);
    return false;
}
