#ifndef BX_APPLETS_SYSTEM_SCREEN_CONFIG_H
#define BX_APPLETS_SYSTEM_SCREEN_CONFIG_H

#define HAVE_DIRENT_H 1
#define HAVE_EXECVPE 1
#define HAVE_LANGINFO_H 1
#define HAVE_OPENPTY 1
#define HAVE_PTY_H 1
#define HAVE_SETEUID 1
#define HAVE_SETRESUID 1
#define HAVE_SETREUID 1
#define HAVE_STRERROR 1
#define HAVE_UTIMES 1

#define PTY_GROUP 5
#define PTY_MODE 0620

#define VERSION_MAJOR 5
#define VERSION_MINOR 0
#define VERSION_REVISION 1

#endif /* BX_APPLETS_SYSTEM_SCREEN_CONFIG_H */
