#ifndef BX_APPLETS_NETWORK_MIRA_OPTIONS_H
#define BX_APPLETS_NETWORK_MIRA_OPTIONS_H

#include <getopt.h>
#include <stdbool.h>
#include <stddef.h>

typedef enum {
    MIRA_OPTION_CATEGORY_STARTUP = 0,
    MIRA_OPTION_CATEGORY_DOWNLOAD,
    MIRA_OPTION_CATEGORY_DIRECTORIES,
    MIRA_OPTION_CATEGORY_HTTP,
    MIRA_OPTION_CATEGORY_TLS,
    MIRA_OPTION_CATEGORY_RECURSIVE,
    MIRA_OPTION_CATEGORY_UNSUPPORTED,
} MiraOptionCategory;

typedef struct {
    const char* name;
    int value;
    int has_arg;
    const char* alias;
    const char* metavar;
    const char* description;
    MiraOptionCategory category;
    bool supported;
} MiraOptionSpec;

enum {
    MIRA_OPT_NO_VERBOSE = 1000,
    MIRA_OPT_OUTPUT_FILE,
    MIRA_OPT_APPEND_OUTPUT,
    MIRA_OPT_DEBUG,
    MIRA_OPT_INPUT_FILE,
    MIRA_OPT_FORCE_HTML,
    MIRA_OPT_BASE,
    MIRA_OPT_REJECTED_LOG,
    MIRA_OPT_RETRY_CONNREFUSED,
    MIRA_OPT_RETRY_ON_HTTP_ERROR,
    MIRA_OPT_NO_CLOBBER,
    MIRA_OPT_PROGRESS,
    MIRA_OPT_SHOW_PROGRESS,
    MIRA_OPT_NO_IF_MODIFIED_SINCE,
    MIRA_OPT_NO_USE_SERVER_TIMESTAMPS,
    MIRA_OPT_SPIDER,
    MIRA_OPT_DRY_RUN,
    MIRA_OPT_DNS_SERVERS,
    MIRA_OPT_BIND_DNS_ADDRESS,
    MIRA_OPT_DNS_TIMEOUT,
    MIRA_OPT_CONNECT_TIMEOUT,
    MIRA_OPT_READ_TIMEOUT,
    MIRA_OPT_WAITRETRY,
    MIRA_OPT_RANDOM_WAIT,
    MIRA_OPT_MAX_THREADS,
    MIRA_OPT_NO_PROXY,
    MIRA_OPT_BIND_ADDRESS,
    MIRA_OPT_LIMIT_RATE,
    MIRA_OPT_NO_DNS_CACHE,
    MIRA_OPT_RESTRICT_FILE_NAMES,
    MIRA_OPT_PREFER_FAMILY,
    MIRA_OPT_USER,
    MIRA_OPT_PASSWORD,
    MIRA_OPT_UNLINK,
    MIRA_OPT_XATTR,
    MIRA_OPT_NO_DIRECTORIES,
    MIRA_OPT_NO_HOST_DIRECTORIES,
    MIRA_OPT_PROTOCOL_DIRECTORIES,
    MIRA_OPT_CUT_DIRS,
    MIRA_OPT_HTTP_USER,
    MIRA_OPT_HTTP_PASSWORD,
    MIRA_OPT_DEFAULT_PAGE,
    MIRA_OPT_HEADER,
    MIRA_OPT_MAX_REDIRECT,
    MIRA_OPT_REDIRECT_METHOD,
    MIRA_OPT_PARANOID,
    MIRA_OPT_PROXY_USER,
    MIRA_OPT_PROXY_PASSWORD,
    MIRA_OPT_REFERER,
    MIRA_OPT_SAVE_HEADERS,
    MIRA_OPT_NO_HTTP_KEEP_ALIVE,
    MIRA_OPT_NO_COOKIES,
    MIRA_OPT_LOAD_COOKIES,
    MIRA_OPT_SAVE_COOKIES,
    MIRA_OPT_KEEP_SESSION_COOKIES,
    MIRA_OPT_POST_DATA,
    MIRA_OPT_POST_FILE,
    MIRA_OPT_METHOD,
    MIRA_OPT_CONTENT_DISPOSITION,
    MIRA_OPT_AUTH_NO_CHALLENGE,
    MIRA_OPT_HTTPS_ONLY,
    MIRA_OPT_NO_CHECK_CERTIFICATE,
    MIRA_OPT_CERTIFICATE,
    MIRA_OPT_PRIVATE_KEY,
    MIRA_OPT_CA_CERTIFICATE,
    MIRA_OPT_CA_DIRECTORY,
    MIRA_OPT_PINNEDPUBKEY,
    MIRA_OPT_NO_HSTS,
    MIRA_OPT_HSTS_FILE,
    MIRA_OPT_FTP_USER,
    MIRA_OPT_FTP_PASSWORD,
    MIRA_OPT_NO_PASSIVE_FTP,
    MIRA_OPT_CONVERT_FILE_ONLY,
    MIRA_OPT_BACKUPS,
    MIRA_OPT_ACCEPT_REGEX,
    MIRA_OPT_REGEX_TYPE,
    MIRA_OPT_EXCLUDE_DOMAINS,
    MIRA_OPT_TRUST_SERVER_NAMES,
    MIRA_OPT_NO_PARENT,
};

const struct option* bx_mira_long_options(void);
const char* bx_mira_short_options(void);
const MiraOptionSpec* bx_mira_option_specs(size_t* count_out);
const MiraOptionSpec* bx_mira_option_spec_for_value(int value);

#endif
